git:
  hosts:
    git01:
      ansible_host: 159.8.76.123
      ansible_user: root
      env: integration

jenkins:
  hosts:
    jenkins01:
      ansible_host: 159.8.76.125
      ansible_user: root
      env: integration

supervision:
  hosts:
    supervision01:
      ansible_host: 159.8.76.116
      ansible_user: root
      env: integration

webserver:
  hosts:
    webserver01:
      ansible_host: 16.170.202.186
      ansible_user: root
      env: preprod
    webserver02:
      ansible_host: 13.53.35.243
      ansible_user: root
      env: preprod
